language: python

# safelist
branches:
  only:
  - dev

services:
  - mongodb

install:
- echo $TRAVIS_PYTHON_VERSION
- sudo apt-get install gcc
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install 'numpy>=1.11,<1.12'; else pip install -U numpy; fi
- if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install pandas; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -U sphinx; fi
- pip install -U pymongo


python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then cd doc && PYTHONPATH=.. make doctest; fi

