language: python

# safelist
branches:
  only:
  - dev

services:
  - mongodb

env:
  - BSON_DIR=`pwd`/libbson/bson-build LD_LIBRARY_PATH=$BSON_DIR/lib:$LD_LIBRARY_PATH

install:
- echo $BSON_DIR
- echo $LD_LIBRARY_PATH
- echo $TRAVIS_PYTHON_VERSION
- sudo apt-get install git-core automake autoconf libtool gcc
- git clone git://github.com/mongodb/libbson.git
- cd libbson/
- mkdir bson-build
- ./autogen.sh --prefix=`pwd`/bson-build
- make
- make install
- cd ..
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install 'numpy>=1.11,<1.12'; else pip install -U numpy; fi
- pip install -U pymongo sphinx


python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then cd doc && PYTHONPATH=.. make doctest; fi

